config/routes.rb
Rails.application.routes.draw do
  resources :registros
  resources :conceptospersonales
  resources :conceptopersonales
  resources :dependencias
  resources :conceptos
  devise_for :usuarios
  get 'welcome/index'
  resources :settings
  resources :personas do
  member do
    post 'cambiarestado'
    post 'enviar'
  end
end
  resources :tipos
  resources :cargos
  resources :departamentos

   root 'welcome#index'
   get 'welcome/ayuda'
   get 'welcome/users'

end

app/models/dependencia.rb
class Dependencia < ActiveRecord::Base
  resourcify
    validates :nombre, uniqueness: { case_sensitive: false }, presence: true
    has_many :departamentos, dependent: :destroy
    after_create :logc
    after_destroy :logd
    after_update :logu

  include Rails.application.routes.url_helpers
  def logc
    log(id.to_s,changes.to_json.to_s, 3, 0)
  end

  def logu
    log(id.to_s, changes.to_json.to_s, 3, 1)
  end

  def logd
    log(id.to_s,"{}".to_json, 3, 2)
  end
end

app/controllers/dependencias_controller.rb
class DependenciasController < ApplicationController
  before_filter :authenticate_usuario!

  before_action :set_dependencia, only: [:edit, :update, :destroy]

  # GET /dependencias
  # GET /dependencias.json
  def index
    @dependencias = Dependencia.all
  end

  # GET /dependencias/1
  # GET /dependencias/1.json
  def show
    respond_to do |format|
      format.html { redirect_to dependencias_path, notice: 'Ruta no disponible.' }
    end
  end

  # GET /dependencias/new
  def new
    authorize! :create, Dependencia

    @dependencia = Dependencia.new
  end

  # GET /dependencias/1/edit
  def edit
    authorize! :update, Dependencia
  end

  # POST /dependencias
  # POST /dependencias.json
  def create
    authorize! :create, Dependencia
    @dependencia = Dependencia.new(dependencia_params)

    respond_to do |format|
      if @dependencia.save
        format.html { redirect_to dependencias_path, notice: 'La dependencia fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @dependencia }
      else
        format.html { render :new }
        format.json { render json: @dependencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dependencias/1
  # PATCH/PUT /dependencias/1.json
  def update
    authorize! :update, Dependencia
    respond_to do |format|
      if @dependencia.update(dependencia_params)

        format.html { redirect_to dependencias_path, notice: 'Los datos de la dependencia fueron actualizados exitosamente.' }
        format.json { render :show, status: :ok, location: @dependencia }
      else
        format.html { render :edit }
        format.json { render json: @dependencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dependencias/1
  # DELETE /dependencias/1.json
  def destroy
    authorize! :destroy, Dependencia
    @dependencia.destroy
            
    respond_to do |format|
      format.html { redirect_to dependencias_url, notice: 'La dependencia fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dependencia
      if !Dependencia.where(id: params[:id]).empty?
        @dependencia = Dependencia.find(params[:id])
        @lt = '<a href="' + dependencias_path + '"> ' + @dependencia.nombre + '</a>'
      else
        respond_to do |format|
          format.html { redirect_to dependencias_url, alert: 'Dependencia no encontrada en la base de datos.' }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dependencia_params
      params.require(:dependencia).permit(:nombre)
    end
end

app/helpers/dependencias_helper.rb
module DependenciasHelper
end

app/views/dependencias/_form.html.erb
<%= simple_form_for(@dependencia, html: {  role: "form"})   do |f| %>
<%= render 'layouts/errores', x: @dependencia %>
<div class="panel panel-default">
  <div class="panel-heading">
    Datos
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= f.label :nombre %><br>
        <div class="form-group input-group">
          <span class="input-group-addon">
            <span class="fa fa-align-justify"></span>
          </span>
          <%= f.text_field :nombre, class: "form-control", autofocus: "" %>
        </div>
      </div>
      <%= render 'layouts/botones', p: dependencias_path  %>
    </div>
  </div>
</div>
<% end %>

app/views/dependencias/edit.html.erb
<div class="page-header">
  <h1>Editar Dependencia</h1>
</div>

<%= render 'form' %>

app/views/dependencias/index.html.erb
<div class="page-header">
  <%= render 'layouts/nuevo', msg: "Nueva dependencia", path: new_dependencia_path ,x: Dependencia %>

  <h1><i class="fa fa-building-o"></i> Dependencias</h1>
</div>
<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false">Lista de dependencias</li>

  <li class="list-group-item text-center ">
    <%if Dependencia.all.length>0%>
    <div class="table-responsive">
      <table class="table table-hover table-bordered table-condensed table-striped">
        <thead>
          <tr>
            <th class="actions">Nombre</th>
            <% if !current_usuario.has_role?:regular %>
            <th class="actions" style="width: 100px;">Acciones</th>
            <%end%>
          </tr>

        </thead>

        <tbody>

          <% @dependencias.each do |dependencia| %>
          <tr>
            <td><%= dependencia.nombre.upcase %></td>
<% if !current_usuario.has_role?:regular %>
            <td class="actions">
              <%= render 'layouts/actions', x: Dependencia, y: edit_dependencia_path(dependencia), z: dependencia %>
            </td>
              <%end%>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
  <%else%>
  <div class="actions">
    <h4>"No hay dependencias disponibles"</h4>
  </div>
  <%end%>
</ul>

app/views/dependencias/new.html.erb
<div class="page-header">
  <h1>Agregar Dependencia</h1>
</div>

<%= render 'form' %>