config/routes.rb
Rails.application.routes.draw do
  resources :registros
  resources :conceptospersonales
  resources :conceptopersonales
  resources :dependencias
  resources :conceptos
  devise_for :usuarios
  get 'welcome/index'
  resources :settings
  resources :personas do
  member do
    post 'cambiarestado'
    post 'enviar'
  end
end
  resources :tipos
  resources :cargos
  resources :departamentos

   root 'welcome#index'
   get 'welcome/ayuda'
   get 'welcome/users'

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  resourcify
  belongs_to :departamento
  has_one :persona, dependent: :destroy
  belongs_to :tipo
  has_many :sueldos, dependent: :destroy
  has_many :historiales, dependent: :destroy
  accepts_nested_attributes_for :sueldos
  validates :nombre, presence: true
  validates :departamento_id, presence: true
  validates :tipo_id, presence: true
  attr_readonly :departamento_id, :tipo_id
  self.per_page = 10
  before_update :actualizar
  after_create :logc
  after_destroy :logd
  after_update :logu
  attr_accessor :p, :d
  include Rails.application.routes.url_helpers
  def persona_ahora
    personas = Historial.where('cargo_id = ? ', id)

    unless personas.empty?
      personas.each do |c|
        min = 0
        c.fecha_fin = $ahora if c.fecha_fin.nil?
        min = if c.fecha_inicio.day <= 15
                Date.civil(c.fecha_inicio.year, c.fecha_inicio.mon, 1)
              else
                Date.civil(c.fecha_inicio.year, c.fecha_inicio.mon, 16)
              end
        max = 0
        max = if c.fecha_fin.day <= 15
                Date.civil(c.fecha_fin.year, c.fecha_fin.mon, 15)
              else
                Date.civil(c.fecha_fin.year, c.fecha_fin.mon, -1)
              end
        if (min..max).cover?($ahora)
          self.p = c.persona
          self.d = false
        else
          self.d = true
        end
      end
    end
  end

  def logc
    if changes.include?(:nombre) || changes.include?(:tipo_id) || changes.include?(:departamento_id)
      log(id.to_s, changes.to_json.to_s, 6, 0)
    end
  end

  def logu
    if changes.include?(:nombre) || changes.include?(:tipo_id) || changes.include?(:departamento_id)
      log(id.to_s, changes.to_json.to_s, 6, 1)
    end
  end

  def logd
    log(id.to_s, '{}'.to_json, 6, 2)
  end

  def truncar_sueldo
    sueldos.last.monto = truncar(sueldos.last.monto)
    sueldos.last.sueldo_integral = truncar(sueldos.last.sueldo_integral)
  end

  def actualizar
    return unless sueldos.last.monto_changed? || sueldos.last.sueldo_integral_changed?

    nuevo = false
    if $quincena == 0
      nuevo = Sueldo.where(cargo_id: id).where(created_at: Time.now.beginning_of_month..(Time.now.beginning_of_month + 14.days)).empty?
    else
      nuevo = Sueldo.where(cargo_id: id).where(created_at: (Time.now.beginning_of_month + 15.days)..Time.now.end_of_month).empty?
    end

    if nuevo
      viejo = Sueldo.where(cargo_id: id).where(activo: true).last
      nmonto = sueldos.last.monto
      nsueldo_integral = sueldos.last.sueldo_integral
      sueldos.last.activo = false
      sueldos.last.monto = viejo.monto
      sueldos.last.sueldo_integral = viejo.sueldo_integral
      crear = sueldos.new
      crear.monto = truncar(nmonto)
      crear.sueldo_integral = truncar(nsueldo_integral)
    else
      truncar_sueldo
    end
  end

  def self.search(search, dep)
    search = search.downcase
    if dep == '' && search == ''
      order(:nombre)
    elsif dep && dep != '' && search == ''
      where('departamento_id = CAST(? AS INTEGER)', dep)
    elsif dep && dep != ''
      where('(LOWER(nombre) LIKE ? ) AND departamento_id = CAST(? AS INTEGER)', "%#{search}%", dep)
    elsif search && search != ''
      where('LOWER(nombre) LIKE ? ', "%#{search}%")
    end
  end
end

app/controllers/cargos_controller.rb
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
# encoding: utf-8
class CargosController < ApplicationController
    before_filter :authenticate_usuario!
    before_action :set_cargo, only: [:show, :edit, :update, :destroy]

    # GET /cargos
    # GET /cargos.json
    def index
        s = params[:search]
        d = params[:departamento]
        p = params[:page]
        buscar = ((s != '' && s) || d)

        @cargos = buscar ? Cargo.all.search(s, d).paginate(page: p) : Cargo.order(:nombre).paginate(page: p)
    end

    # GET /cargos/1
    # GET /cargos/1.json
    def show
    end

    # GET /cargos/new
    def new
        authorize! :create, Cargo
        @cargo = Cargo.new
        @cargo.sueldos.build
    end

    # GET /cargos/1/edit
    def edit
        authorize! :update, Cargo
    end

    # POST /cargos
    # POST /cargos.json
    def create
        authorize! :create, Cargo
        @cargo = Cargo.new(cargo_params)
        # @sueldo= Sueldo.new(cargo_params['sueldo_attributes'])
        respond_to do |format|
            if @cargo.save

                format.html { redirect_to @cargo, notice: 'El cargo fue creado exitosamente.' }
                format.json { render :show, status: :created, location: @cargo }
            #  @sueldo.save
            else
                format.html { render :new }
                format.json { render json: @cargo.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /cargos/1
    # PATCH/PUT /cargos/1.json
    def update
        authorize! :update, Cargo
        respond_to do |format|

            if @cargo.update(cargo_params)


                format.html { redirect_to @cargo, notice: 'Los datos del cargo fueron actualizados exitosamente.' }
                format.json { render :show, status: :ok, location: @cargo }
            else
                format.html { render :edit }
                format.json { render json: @cargo.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /cargos/1
    # DELETE /cargos/1.json
    def destroy
        authorize! :destroy, Cargo
        @cargo.destroy
        

        respond_to do |format|
            format.html { redirect_to cargos_url, notice: 'El cargo fue eliminado exitosamente.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
        if !Cargo.where(id: params[:id]).empty?
            @cargo = Cargo.find(params[:id])

        else
            respond_to do |format|
                format.html { redirect_to cargos_url, alert: 'Cargo no encontrado en la base de datos.' }
            end
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
        params.require(:cargo).permit(:nombre, :tipo_id, :departamento_id, sueldos_attributes: [:id, :monto, :activo, :sueldo_integral, :_destroy])
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_cargo.html.erb
<li class="list-group-item text-center ">
<%if p.length>0%>

  <div class="table-responsive">
        <table class="table table-hover table-bordered table-condensed table-striped">
          
      <thead>
        <tr>
          <th class="actions">Nombre</th>
          <th class="actions">Departamento</th>
          <th class="actions">Sueldo Básico</th>
          <th class="actions">Sueldo Integral</th>
          <th class="actions">Nómina</th>
          <th class="actions">Disponible</th>
          <th class="actions" style="width: 100px;">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% p.each do |cargo| %>
        <tr>
          <td><%= cargo.nombre.upcase %></td>
          <td><%= cargo.departamento.nombre.upcase %></td>
          <td><%= tr(cargo.sueldos.last.monto) %></td>
          <td><%= tr(cargo.sueldos.last.sueldo_integral) %></td>
          <td><%= cargo.tipo.nombre.upcase %></td>
          <td><%if cargo.disponible %>
            <span class="fa fa-check"></span>
            <%else%>
            <span class="fa fa-remove"></span>
            <%end%></td>
          <td class="actions">
            <div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
              <%= render 'layouts/actions', x: Cargo, y: edit_cargo_path(cargo), z: cargo %>

            </td>

          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="pagination ">
      <%= will_paginate p, renderer: BootstrapPagination::Rails %>
    </div>

    <%else%>
    <div class="actions">
      <h4>"No hay cargos disponibles"</h4>
    </div>
    <%end%>
  </li>

app/views/cargos/_form.html.erb
<%= simple_form_for(@cargo, html: {  role: "form"})   do |f| %>
<%= render 'layouts/errores', x: @cargo %>
<div class="panel panel-default">
  <div class="panel-heading">
    Datos
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-12">
        <div class="col-xs-6">
          <%= f.label :nombre %><br>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-align-justify"></span>
            </span>
            <%= f.text_field :nombre, class: "form-control input-text", autofocus:"", hint:"Sueldo basico que se gana en este cargo."%>
          </div>
        </div>
        <div class="col-xs-6">
          <%= f.label :departamento_id %><br>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-building-o"></span>
            </span>
            <%  d =(Cargo._attr_readonly.include?("departamento_id") and f.object.departamento_id.nil? == false) ? "disabled" : " "%>

            <%= f.select(:departamento_id, options_for_select(Departamento.all.map{|s|[s.nombre, s.id]}, f.object.departamento_id),{include_blank:'Seleccione un departamento...'},class: "form-control","#{d}": true)  %>
          </div>
        </div>
        <div class="col-xs-6">
          <%= f.label :tipo_id %><br>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-align-justify"></span>
            </span>
            <%  d =(Cargo._attr_readonly.include?("tipo_id") and f.object.tipo_id.nil? == false) ? "disabled" : " "%>

            <%= f.select(:tipo_id, options_for_select(Tipo.all.map{|s|[s.nombre, s.id]}, f.object.tipo_id),{include_blank:'Seleccione una nómina...'},class: "form-control","#{d}": true)  %>
          </div>
        </div>
        <%= f.fields_for :sueldos  do |sueldo_builder|  %>
        <% if sueldo_builder.object.activo? %>

        <div class="col-xs-6">
          <%= sueldo_builder.label :monto %>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-money"></span>
            </span>
            <%= sueldo_builder.text_field :monto,class: "form-control"%>
          </div>
        </div>
        <div class="col-xs-6">
          <%= sueldo_builder.label :sueldo_integral %>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-money"></span>
            </span>
            <%= sueldo_builder.text_field :sueldo_integral,class: "form-control" %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      <%= render 'layouts/botones', p: cargos_path  %>
    </div>
  </div>
</div>
<% end %>

app/views/cargos/edit.html.erb
<div class="page-header">
  <h1>Editar Cargo</h1>
</div>

<%= render 'form' %>

app/views/cargos/index.html.erb
<div class="page-header">

  <%= render 'layouts/nuevo', msg: "Nuevo cargo", path: new_cargo_path ,x: Cargo%>

  <h1><i class="fa fa-briefcase"></i> Cargos</h1>
</div>
<ul class="list-group">

  <li class="list-group-item text-muted" contenteditable="false">Búsqueda</li>
  <li class="list-group-item ">

    <div class="input-group">
      <div class="input-group-btn">
        <button id="departamentos" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Todos los departamentos
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li class=" disabled">
            <a href="#" class="departamento" id="">Todos los departamentos</a>
          </li>
          <%@departamentos=Departamento.all

        @departamentos.each do |c|%>
          <%=  raw("<li><a href=\"#\" class=\"departamento\" id=\""+c.id.to_s+"\">"+c.nombre.capitalize+"</a></li>") %>
          <%end%>

        </ul>

      </div>
      <input type="text" class="form-control" placeholder="Buscar por nombre del cargo..." name="search" id="search" value="<%= params[:search]%>">
      <input type="text" id="departamento_search" value="" hidden="hidden">

      <span class="input-group-addon">
        <span id="search_icon" class="fa fa-search"></span>

      </span>
    </div>
  </li>
</ul>
<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false">Lista de cargos</li>
  <div class="sort_paginate_ajax  text-center">
    <%= render 'cargo', p: @cargos %>
  </div>

</ul>
<script>
  var classes = ".sort_paginate_ajax th a, .sort_paginate_ajax .pagination a";
  var delay = (function () {
    var timer = 0;
    return function (callback, ms) {
      clearTimeout(timer);
      timer = setTimeout(callback, ms);
    };
  })();

  function loading() {
    $("#search_icon").attr("class", "fa fa-refresh fa-spin fa-fw")
  }
  function query() {
    loading();
    return "/cargos?page=1&search=" + $("#search").val() + "&departamento=" + $("#departamento_search").val();

  }
  $(function () {

    $(".departamento").click(function () {
      $(".departamento").parent().attr("class", "");
      $(this).parent().attr("class", "disabled")
      $("#departamentos").html($(this).html() + '<span class="caret"></span>');
      $("#departamento_search").val($(this).attr("id"));
      $.getScript(query());

      return false;
    });
    $("#search").keyup(function () {
      delay(function () {
        $.getScript(query());

        return false;
      }, 500);
    });
    $(classes).click(function () {
      $.getScript(this.href);
      return false;
    });
  });
</script>

app/views/cargos/index.js.erb
$('.sort_paginate_ajax').html("<%= escape_javascript(render "cargo", p: @cargos)%>");
$(classes).click(function(){$.getScript(this.href); return false;} );
$("#search_icon").attr("class","fa fa-search")

app/views/cargos/new.html.erb
<div class="page-header">
  <h1> Agregar Cargo </h1>
</div>

<%= render 'form' %>

app/views/cargos/show.html.erb
<div class="page-header">
  <h2><%= @cargo.nombre.upcase %></h2>
  <% ocupado_por=Persona.where("cargo_id=#{@cargo.id}").first%>
  <h4>
    <b>Departamento:</b>
    <%= @cargo.departamento.nombre.upcase %>
    <%if ocupado_por%>
    ,
    <b>Ocupado por:</b>
    <%= (ocupado_por.nombres + " "+ocupado_por.apellidos).upcase %>
    ,
    </h4>
    <h4>
    <b>Desde:</b>
    <%= ocupado_por.contrato.fecha_inicio%>
    <%end%>
  </h4>
</div>

<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false">Sueldos</li>
  <li class="list-group-item text-center">
    <div class="table-responsive">
      <table class="table table-hover table-responsive table-condensed table-bordered">
        <thead>
          <tr>
            <th class="actions">Sueldo Base</th>
            <th class="actions">Sueldo Integral</th>
            <th class="actions">Fecha de vigencia</th>
            <th class="actions" style="width:20px">Activo</th>
          </tr>
        </thead>

        <tbody>
          <% @cargo.sueldos.order('activo DESC').each do |sueldo| %>
          <tr class="<%= sueldo.activo ? 'success': 'danger'%>">
            <td><%= tr(sueldo.monto) %></td>
            <td><%= tr(sueldo.sueldo_integral) %></td>
            <%
            quincena=(sueldo.created_at.day<=15)? 0 : 1
            %>
            <th class="actions"><%= sueldo.created_at.strftime("#{$dic['quincena'].key(quincena)} #{$dic['meses'].key(sueldo.created_at.month).capitalize}-%Y") %></th>
            <th class="actions"><%if sueldo.activo %>
              <span class="fa fa-check"></span>
              <%else%>
              <span class="fa fa-close"></span>
              <%end%></th>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
</ul>

<div class="col-xs-12 actions"><br>
  <%= link_to raw('<i class= "fa fa-pencil"></i> Editar'), edit_cargo_path(@cargo), class: "btn btn-success boton" %>
  <%= link_to raw('<i class= "fa fa-arrow-circle-left"></i> Regresar'), cargos_path, class: "btn btn-default boton" %>
</div>