config/routes.rb
Rails.application.routes.draw do
  resources :registros
  resources :conceptospersonales
  resources :conceptopersonales
  resources :dependencias
  resources :conceptos
  devise_for :usuarios
  get 'welcome/index'
  resources :settings
  resources :personas do
  member do
    post 'cambiarestado'
    post 'enviar'
  end
end
  resources :tipos
  resources :cargos
  resources :departamentos

   root 'welcome#index'
   get 'welcome/ayuda'
   get 'welcome/users'

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  resourcify
  belongs_to :dependencia
  has_many :cargos ,  dependent: :destroy
  validates :nombre, uniqueness: { case_sensitive: false }, presence: true
  validates :dependencia_id, presence: true
  attr_readonly :dependencia_id
  after_create :logc
  after_destroy :logd
  after_update :logu

include Rails.application.routes.url_helpers
def logc
  log(id.to_s,changes.to_json.to_s, 2, 0)
end

def logu
  log(id.to_s, changes.to_json.to_s, 2, 1)
end

def logd
  log(id.to_s,"{}".to_json, 2, 2)
end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_filter :authenticate_usuario!

  before_action :set_departamento, only: [:edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    respond_to do |format|
      format.html { redirect_to departamentos_path, notice: 'Ruta no disponible.' }
    end
  end

  # GET /departamentos/new
  def new
    authorize! :create, Departamento
    if Dependencia.all.length <=0
    respond_to do |format|
      format.html { redirect_to dependencias_url, notice: 'Es necesario agregar dependencia.'  }
      format.json { render json: @persona.errors, status: "Es necesario agregar dependencia." }
    end
  else
    @departamento = Departamento.new
    end
  end

  # GET /departamentos/1/edit
  def edit
    authorize! :update, Departamento
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    authorize! :create, Departamento
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save

        format.html { redirect_to departamentos_path, notice: 'El departamento fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    authorize! :update, Departamento
    respond_to do |format|
      if @departamento.update(departamento_params)

        format.html { redirect_to departamentos_path, notice: 'Los datos del departamento fueron actualizados exitosamente.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    authorize! :destroy, Departamento
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'El departamento fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      if !Departamento.where(id: params[:id]).empty?
        @departamento= Departamento.find(params[:id])
        @lt = '<a href="' + departamentos_path + '"> ' + @departamento.nombre + '</a>'
      else
        respond_to do |format|
          format.html { redirect_to departamentos_url, alert: 'Departamento no encontrado en la base de datos.' }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nombre, :dependencia_id)
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<%= simple_form_for(@departamento, html: {  role: "form"})   do |f| %>
<%= render 'layouts/errores', x: @departamento %>
<div class="panel panel-default">
  <div class="panel-heading">
    Datos
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <div class="col-md-6">
          <%= f.label :nombre %><br>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-align-justify"></span>
            </span>
            <%= f.text_field :nombre, class: "form-control", autofocus: "" %>
          </div>
        </div>
        <div class="col-md-6">
          <%= f.label :dependencia_id %><br>
          <div class="form-group input-group">
            <span class="input-group-addon">
              <span class="fa fa-building-o"></span>
            </span>
            <% if f.object.dependencia_id=f.object.dependencia_id ? f.object.dependencia_id : 0%>
            <%  d =(Departamento._attr_readonly.include?("dependencia_id") and f.object.dependencia_id.nil? == false) ? "disabled" : " "%>

            <%= f.select(:dependencia_id, options_for_select(Dependencia.all.map{|s|[s.nombre, s.id]}, f.object.dependencia_id),{include_blank:'Seleccione una Dependencia...'},class: "form-control","#{d}": true)  %></span>
          <%end%>
        </div>
      </div>
    </div>
    <%= render 'layouts/botones', p: departamentos_path  %>
  </div>
</div>
</div>
<%end%>

app/views/departamentos/edit.html.erb
<div class="page-header">
  <h1>Editar Departamento</h1>
</div>

<%= render 'form' %>

app/views/departamentos/index.html.erb
<div class="page-header">
  <%= render 'layouts/nuevo', msg: "Nuevo Departamento", path: new_departamento_path ,x: Departamento %>

  <h1><i class="fa fa-building-o"></i> Departamentos</h1>
</div>
<ul class="list-group">
  <li class="list-group-item text-muted" contenteditable="false">Lista de departamentos</li>

  <li class="list-group-item text-center ">
    <%if Departamento.all.length>0%>
    <div class="table-responsive">
          <table class="table table-hover table-bordered table-condensed table-striped">
            <thead>
          <tr>
            <th class= "actions" ><%=t("nombre")%></th>
            <th class= "actions" >Dependencia</th>
            <th class= "actions" >Personas</th>
<% if !current_usuario.has_role?:regular %>
            <th  class= "actions" style= "width: 100px;">Acciones</th>
            <%end%>
          </tr>
        </thead>

        <tbody>
          <% @departamentos.each do |departamento| %>
          <tr>
            <td><%= departamento.nombre.upcase %></td>
            <td><%= departamento.dependencia.nombre.upcase %></td>
            <td><%=Cargo.where("departamento_id=#{departamento.id} and disponible=false").length %></td>
<% if !current_usuario.has_role?:regular %>
            <td>
              <%= render 'layouts/actions', x: Departamento, y: edit_departamento_path(departamento), z: departamento %>

            </td>
            <%end%>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </li>
  <%else%>
  <div class="actions">
    <h4>"No hay departamentos disponibles"</h4>
  </div>
  <%end%>
</ul>

app/views/departamentos/new.html.erb
<div class="page-header">
  <h1>Agregar Departamento</h1>
</div>

<%= render 'form' %>