config/routes.rb
Rails.application.routes.draw do
  resources :registros
  resources :conceptospersonales
  resources :conceptopersonales
  resources :dependencias
  resources :conceptos
  devise_for :usuarios
  get 'welcome/index'
  resources :settings
  resources :personas do
  member do
    post 'cambiarestado'
    post 'enviar'
  end
end
  resources :tipos
  resources :cargos
  resources :departamentos

   root 'welcome#index'
   get 'welcome/ayuda'
   get 'welcome/users'

end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  resourcify
  has_many :cargos,  dependent: :destroy
  has_and_belongs_to_many :conceptos
    validates :nombre, uniqueness: true, presence: true
    after_create :logc
    after_destroy :logd
    after_update :logu

  include Rails.application.routes.url_helpers
  def logc
    log(id.to_s,changes.to_json.to_s, 5, 0)
  end

  def logu
    log(id.to_s, changes.to_json.to_s, 5, 1)
  end

  def logd
    log(id.to_s,"{}".to_json, 5, 2)
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end
  def txt

  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
    respond_to do |format|
      format.html { redirect_to tipos_path, notice: 'Ruta no disponible.' }
      format.json
      format.txt do
        send_data 'text to send', :filename => 'some.txt'
      end
      format.pdf do
        case params[:doc]
        when '0'
          pdf = RecibosPdf.new(@tipo, 0, params[:c],params[:cp])
          file = "Recibos_#{@tipo.nombre}"
        when '1'
          pdf = RecibosPdf.new(@tipo, 1, params[:c],params[:cp])
          file = "Recibos_#{@tipo.nombre}_ECO"
        when '2'
          pdf = BancariosPdf.new(@tipo, 0, params[:c],params[:cp])
          file = "Bancarios_#{@tipo.nombre}"
        when '3'
          pdf = BancariosPdf.new(@tipo, 1, params[:c],params[:cp])
          file = "Bancarios_#{@tipo.nombre}_ECO"
        when '4'
          pdf = ConceptosPdf.new(@tipo, 0, params[:c],params[:cp])
          file = "Conceptos_#{@tipo.nombre}"
        when '5'
          pdf = ConceptosPdf.new(@tipo, 1, params[:c],params[:cp])
          file = "Conceptos_#{@tipo.nombre}_ECO"
        end
        send_data pdf.render, filename: file, type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  # GET /tipos/new
  def new
    authorize! :create, Tipo
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
    authorize! :update, Tipo
  end

  # POST /tipos
  # POST /tipos.json
  def create
    authorize! :create, Tipo
    @tipo = Tipo.new(tipo_params)


    respond_to do |format|
      if @tipo.save
        format.html { redirect_to tipos_path, notice: 'La nómina fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    authorize! :update, Tipo
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to tipos_path, notice: 'Los datos de la nómina fueron actualizados exitosamente.' }
        format.json { head :no_content }
      end
    end
  end

  def destroy
    authorize! :destroy, Tipo
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'La nómina fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end
protected
def data_txt
  
end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tipo
    if(Tipo.where(id: params[:id] ).length>0)
    @tipo = Tipo.find(params[:id])
      @lt= '<a href="'+tipos_path+'"> '+@tipo.nombre+'</a>'
    else
      respond_to do |format|
          format.html { redirect_to tipos_url, alert: 'Nomina no encontrada en la base de datos.' }
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tipo_params
    params.require(:tipo).permit(:nombre)
  end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= simple_form_for(@tipo, html: {  role: "form"})   do |f| %>
<%= render 'layouts/errores', x: @tipo %>
<div class="panel panel-default">
  <div class="panel-heading">
    Datos
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= f.label :nombre %><br>
        <div class="form-group input-group">
          <span class="input-group-addon">
            <span class="fa fa-align-justify"></span>
          </span>
          <%= f.text_field :nombre, class: "form-control", autofocus: "" %>
        </div>
      </div>
      <%= render 'layouts/botones', p: tipos_path  %>
    </div>
  </div>
</div>
<% end %>

app/views/tipos/edit.html.erb
<div class="page-header">
  <h1>Editar Nómina</h1>
</div>
<%= render 'form' %>

app/views/tipos/index.html.erb
<div class="page-header">

  <%= render 'layouts/nuevo', msg: "Nueva Nómina", path: new_tipo_path, x: Tipo %>
  <button class="btn btn-default pull-right" style="margin-right:1%; height:111%;" type="button" data-toggle="modal" data-target="#myModal">
    <i class="fa fa-file-pdf-o">
      Reportes</i>
  </button>
  <!-- Modal -->
  <div class="modal fade" id="myModal" style="margin-top:60px;" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">
            <i class="fa fa-file-pdf-o fa-2x"></i>
            Generador de Reportes</h4>
        </div>
        <div class="modal-body">
          <div class="col-xs-12 form-group">
            <%= label_tag "Nómina " %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-bars fa-fw"></span>
              </span>

              <%= select_tag("Tipo",options_for_select(Tipo.all.map{|s|[s.nombre, s.id]}),{include_blank:'Seleccione una nómina...',class: "form-control" }) %>

            </div>
          </div>

          <div class="col-xs-12 form-group">
            <%= label_tag "Quincena" %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-calendar fa-fw"></span>
              </span>

              <select class="form-control" id="quincena">
                <option value="">Seleccione la quincena...</option>
                <%
sueldo=Sueldo.first.created_at if Sueldo.all.length>0
sueldo = Date.today - 1.day if !sueldo

i=1

while sueldo<$ahora

%>
                <%

quincena = (sueldo.day <= 15) ? 0 : 1
dia= (quincena==0) ? 11 : 17
fecha="#{dia}-#{sueldo.month}-#{sueldo.year}"
%>
                <%=raw("<option value=\"#{fecha}\"> #{$dic['quincena'].key(quincena)} #{$dic['meses'].key(sueldo.month)} del #{sueldo.year}</option>")%>
              <%
if quincena==0
  sueldo= Date.strptime("16-#{sueldo.mon}-#{sueldo.year}", '%d-%m-%Y')
else
if sueldo.mon==12
  sueldo=Date.strptime("1-1-#{sueldo.year+1}", '%d-%m-%Y')
else
  sueldo= Date.strptime("1-#{sueldo.mon+1}-#{sueldo.year}", '%d-%m-%Y')
end
end
%>
                <%end%>

              </select>
            </div>
          </div>
          <div class="col-xs-12 form-group">
            <%= label_tag "Tipo de reporte" %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-file fa-fw"></span>
              </span>

              <%= select_tag("tipo_de_reporte",options_for_select($dic["tipos_de_reporte"]),{include_blank:'Seleccione un tipo de Reporte ...',class: "form-control" }) %>

            </div>
          </div>
          <div class="col-xs-12">
            <div class="col-xs-6 form-group">
            <%= label_tag "Conceptos Globales" %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-money fa-fw"></span>
              </span>

              <%= select_tag("Concepto",options_for_select(Concepto.all.map{|s|[s.nombre, s.id]}.prepend([t('Ninguno'), 0])),{include_blank:'Todos (Excepto extras)',class: "form-control" }) %>

            </div>
          </div>
          <div class="col-xs-6 form-group">
            <%= label_tag "Conceptos Personales" %>
            <div class="form-group input-group">
              <span class="input-group-addon">
                <span class="fa fa-money fa-fw"></span>
              </span>

              <%= select_tag("Conceptopersonal",options_for_select(Conceptopersonal.all.map{|s|[s.nombre, s.id]}.prepend([t('Ninguno'), 0])),{include_blank:'Todos (Excepto extras)',class: "form-control" }) %>

            </div>
          </div>
        </div>
        </br>
      </br>
    </br>
  </br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

</div>
<div class="modal-footer">
<div class="btn-group btn-group-md form-inline" role="group" aria-label="...">
<button type="button" class="btn btn-primary" id="generar_boton" name="button">
<i class="fa fa-cog"></i>
Generar</button>
<button type="button" class="btn btn-success" id="generar_boton_eco" name="button">
<i class="fa fa-leaf"></i>
</button>
</div>
<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
</div>
</div>
</div>
</div>
<h1>  <span class="fa-stack  fa-fw," style="font-size: 0.7em;">
    <i class="fa fa-user fa-stack-2x" style="color:black;"></i>
    <i class="fa fa-money fa-stack-1x" style="color:white; margin-top:0.5em; margin-left:0.3em;"></i>
  </span> Tipos de Nómina</h1>
</div>

<ul class="list-group">
<li class="list-group-item text-muted" contenteditable="false">Lista de nóminas</li>
<li class="list-group-item text-center ">
<%if Tipo.all.length>0%>
<div class="table-responsive">

<table class="table table-hover table-bordered table-condensed table-striped">
<thead>
<th class="actions">Nombre</th>

<th class="actions" style="width: 400px;">Reportes</th>
<% if !current_usuario.has_role?:regular%>
<th class="actions" style="width: 100px;">Acciones</th>
<%end%>
</tr>
</thead>

<tbody>
<% @tipos.each do |tipo| %>

<tr>
<td><%= tipo.nombre.upcase %></td>
<td class="actions">
<div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
<%= link_to ' Recibos', tipo_path(tipo,format: "pdf")+"?doc=0&cp=&c=","target": "_blank",class: "btn btn-default fa fa-file-pdf-o reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar recibos de pago" %>
<%= link_to '', tipo_path(tipo,format: "pdf")+"?doc=1&cp=&c=","target": "_blank",class: "btn btn-default fa fa-leaf reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar version Ecologica (ahorro de tinta)" %>
</div>
<div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
<%= link_to ' Bancario', tipo_path(tipo,format: "pdf")+"?doc=2&cp=&c=","target": "_blank",class: "btn btn-default fa fa-file-pdf-o reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar reporte bancario" %>
<%= link_to '', tipo_path(tipo,format: "pdf")+"?doc=3&cp=&c=","target": "_blank",class: "btn btn-default fa fa-leaf reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar version Ecologica (ahorro de tinta)" %>
<%= link_to '', tipo_path(tipo,format: "txt"),"target": "_blank",class: "btn btn-default fa fa-file-text-o reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar en formato txt" %>
</div>
<div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
<%= link_to ' Deducciones', tipo_path(tipo,format: "pdf")+"?doc=4&cp=&c=","target": "_blank",class: "btn btn-default fa fa-file-pdf-o reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar reporte de conceptos" %>
<%= link_to '', tipo_path(tipo,format: "pdf")+"?doc=5&cp=&c=","target": "_blank",class: "btn btn-default fa fa-leaf reportes","data-toggle"=>"tooltip", "data-placement"=>"right", "title"=>"Descargar version Ecologica (ahorro de tinta)" %>
</div>


</td>
<% if !current_usuario.has_role?:regular%>
<td class="actions">
<div class="btn-group btn-group-xs form-inline" role="group" aria-label="...">
<%= render 'layouts/actions', x: Tipo, y: edit_tipo_path(tipo), z: tipo %>
</td>
<%end%>
</tr>

<% end %>
</tbody>
</table>
<br>
<br>
</div>

</li>
</br>
</br>
</br>
</ul>

<script type="text/javascript">

function generar(eco) {

  if ($('#Tipo').val() == '') {
    alert('Seleccione una opcion en el campo nomina.');
    return;
  }
  if ($('#tipo_de_reporte').val() == '') {
    alert('Seleccione una opcion en el campo tipo de reporte.');
    return;
  }
  if ($('#Concepto').val() === "0" && $('#Conceptopersonal').val() === "0") {
    alert('Seleccione al menos una clase de concepto.');
    return;
  }
  var concepto = "&c=" + $('#Concepto').val();

  var conceptopersonal = "&cp=" + $('#Conceptopersonal').val();

  var params = '?doc=' + (parseInt($('#tipo_de_reporte').val()) + eco) + conceptopersonal + concepto + '&ahora=' + $('#quincena').val();
  var win = window.open('<%=tipos_path%>/' + $('#Tipo').val() + '.pdf' + params, '_blank');
  if (win) {
    //Browser has allowed it to be opened
    win.focus();
  } else {
    //Broswer has blocked it
    alert('Please allow popups for this site');
  }
}

$(function () {
  $('[data-toggle="tooltip"]').tooltip();
  $('#generar_boton').click(function () {
    generar(0);
  });
  $('#generar_boton_eco').click(function () {
    generar(1);
  });
});
</script>
<%else%>
<div class="actions">
<h4>"No hay tipos de nómina disponibles"</h4>
</div>
<%end%>

app/views/tipos/new.html.erb
<div class="page-header">
  <h1>Agregar Tipo de Nómina</h1>
</div>

<%= render 'form' %>